<a href="https://colab.research.google.com/github/ola-sumbo/Hamoye-and-ML-with-Ude/blob/master/Hamoye.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#import your library
import numpy as np

In [5]:
#create an array
hamoye = np.array([2,3,5,7,9,11])
hamoye

array([ 2,  3,  5,  7,  9, 11])

In [6]:
type(hamoye)


numpy.ndarray

**Slicing** **through** **arrays**

In [7]:
hamoye[:3]

array([2, 3, 5])

In [8]:
hamoye[3:]

array([ 7,  9, 11])

In [9]:
hamoye[2:4]

array([5, 7])

In [10]:
hamoye[3:5]

array([7, 9])

In [11]:
hamoye[4]

9

In [12]:
hamoye[4] = 26
hamoye

array([ 2,  3,  5,  7, 26, 11])

**Two** **Dimensional Array**

In [13]:
hamoye_2 = np.array([[1,3,5,7], [2,4,6,8]], float)
hamoye

array([ 2,  3,  5,  7, 26, 11])

In [14]:
hamoye_2[1,2]

6.0

In [15]:
hamoye_2[1,0]


2.0

In [16]:
hamoye_2[0,:]


array([1., 3., 5., 7.])

In [17]:
hamoye_2[:,2]


array([5., 6.])

In [18]:
hamoye_2[-1:, -2:]

array([[6., 8.]])

In [19]:
hamoye_2.shape


(2, 4)

In [20]:
hamoye_2

array([[1., 3., 5., 7.],
       [2., 4., 6., 8.]])

In [21]:
hamoye_2[-1:, -2:]

array([[6., 8.]])

In [22]:
hamoye_2[-2, -2]

5.0

**The** "**in**" **statement** **for** **np** **arrays**

In [23]:
23 in hamoye_2

False

In [24]:
8 in hamoye_2

True

In [5]:
hamoye_range = np.array(range(20), float)
hamoye_range

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [6]:
hamoye_range = hamoye_range.reshape((4,5))
hamoye_range

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [7]:
hamoye_range.shape


(4, 5)

In [8]:
a = np.array([1,2,3,4], float)
a.tolist()

[1.0, 2.0, 3.0, 4.0]

In [9]:
list(a)

[1.0, 2.0, 3.0, 4.0]

In [10]:
a.fill(0) 
a

array([0., 0., 0., 0.])

In [12]:
hamoye_range = np.array(range(20), float).reshape(5,4)
hamoye_range

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [13]:
hamoye_range.transpose()


array([[ 0.,  4.,  8., 12., 16.],
       [ 1.,  5.,  9., 13., 17.],
       [ 2.,  6., 10., 14., 18.],
       [ 3.,  7., 11., 15., 19.]])

In [14]:
hamoye_range.flatten()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

**Array Concatenation**

In [15]:
a = np.array([3,5,7], float)
b = np.array([1,11], float)
c = np.array([5,8,9], float)
np.concatenate((a,b,c))

array([ 3.,  5.,  7.,  1., 11.,  5.,  8.,  9.])

In [16]:
x = np.array([[1,2,3], [4,7,9]], float)
y = np.array([[10,12,13], [14,17,19]], float)

In [17]:
np.concatenate((x,y))

array([[ 1.,  2.,  3.],
       [ 4.,  7.,  9.],
       [10., 12., 13.],
       [14., 17., 19.]])

In [18]:
np.concatenate((x,y), axis = 0)


array([[ 1.,  2.,  3.],
       [ 4.,  7.,  9.],
       [10., 12., 13.],
       [14., 17., 19.]])

In [19]:
np.concatenate((x,y), axis = 1)


array([[ 1.,  2.,  3., 10., 12., 13.],
       [ 4.,  7.,  9., 14., 17., 19.]])

**Other Create ways of making arrays**

In [21]:
x.tolist();y.tolist()

[[10.0, 12.0, 13.0], [14.0, 17.0, 19.0]]

In [22]:
np.concatenate((x,y), axis =0)

array([[ 1.,  2.,  3.],
       [ 4.,  7.,  9.],
       [10., 12., 13.],
       [14., 17., 19.]])

In [23]:
np.arange(20, dtype = float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [24]:
np.arange(1,20,3, dtype = float)


array([ 1.,  4.,  7., 10., 13., 16., 19.])

In [25]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**Special Dimensional Arrays**

In [27]:
np.identity(5, dtype = float)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.eye(5, k=-1, dtype = float)     

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

**Array Mathematics**

In [32]:
a = np.array([3,5,7], float)
b = np.array([1,11, 13], float)
c = np.array([5,8,9], float)

In [33]:
a+b+c

array([ 9., 24., 29.])

In [34]:
a-c

array([-2., -3., -2.])

In [35]:
a*b

array([ 3., 55., 91.])

In [36]:
b/c

array([0.2       , 1.375     , 1.44444444])

**Python Numpy Broadcasting**

In [37]:
a = np.array([[1,3], [0,5], [2, -1]], float)

In [38]:
b = np.array([1,11], float)

In [39]:
a + b

array([[ 2., 14.],
       [ 1., 16.],
       [ 3., 10.]])

In [40]:
b = np.array([1,11], float)
b

array([ 1., 11.])

In [41]:
b = np.array([[1,11],[1,11],[1,11]], float)
b

array([[ 1., 11.],
       [ 1., 11.],
       [ 1., 11.]])

**Floor, Ceil and Rint**  **Floor gives the lower integer, Ceil gives the upper integer and rint rounds to the nearest integer **

In [42]:
z = np.array([6.7, 2.3, 5.4, 1.192], float)
z

array([6.7  , 2.3  , 5.4  , 1.192])

In [43]:
np.floor(z)

array([6., 2., 5., 1.])

In [44]:
np.ceil(z)

array([7., 3., 6., 2.])

In [45]:
np.rint(z)

array([7., 2., 5., 1.])

In [46]:
np.e


2.718281828459045

In [47]:
np.pi


3.141592653589793

**Array Iteration**

In [48]:
m = np.array([1,2,5,7,8], float)
m

array([1., 2., 5., 7., 8.])

In [49]:
for hamoye in m:
  print(hamoye)

1.0
2.0
5.0
7.0
8.0


In [50]:
n = np.array([[1,3], [0,5], [2, -1]], float)
n

array([[ 1.,  3.],
       [ 0.,  5.],
       [ 2., -1.]])

In [51]:
for hamoye in n:
  print(hamoye)

[1. 3.]
[0. 5.]
[ 2. -1.]


In [52]:
for (a,b) in n:
  print(a*b)


3.0
0.0
-2.0
