<a href="https://colab.research.google.com/github/ola-sumbo/Hamoye-and-ML-with-Ude/blob/master/Inbuilt_function_that_can_be_utilized_from_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# conversion for importing numpy 
import numpy as np

In [4]:
arr = [6, 7, 8, 9]
type(arr)


list

In [8]:
a = np.array(arr)
type(a)
a.shape
a.dtype

dtype('int64')

In [9]:
# Get dimension with ndim width
print(a.ndim)    #print 1

1


In [12]:
b = np.array([[1,2,3],[4,5,6]])
print(b) 
print(b.ndim)
print(b.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [ ]:
# Inbuilt function used to initialise numpy.py
# a 2 * 3 array generated with random variables
np.random.random

array([[0.44777134, 0.94154716, 0.18433596],
       [0.26216404, 0.36045223, 0.98642724]])

In [25]:
# a 2x3 array of zeros
np.zeros((2, 3))

np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [53]:
# a 3x3 identity matrix
c = np.zeros((3,3), int)
np.fill_diagonal(c,3) 
print(c)


[[3 0 0]
 [0 3 0]
 [0 0 3]]


In [54]:
# Indexing with arrays and using arrays for data processing 
# The elements in the example arrays above can be accessed by indexing like lists in Python such that:
a[3] = 9
b[0, 0] # what is in the matrix of b at position 0 and o by index
b[1, 2] # look for index column 2 from 0 then at position of row 1 from 0
c[0, 1]


0

In [58]:
# Elements in arrays  can also be retrieved by slicing rows and columns or a combination of indexing and slicing.
b[1,  0:2] # skip 1 and print out row 1 from o and column 0 and 2


array([4, 5])

In [61]:
e = np.array([[10, 11, 12],[13, 14, 15], 
              [16, 17, 18],[19, 20, 21]])
e

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [62]:
# slicing
e[:3, :2]  # take every thing except the third row from 0, and take everything except the 2 column from 0

array([[10, 11],
       [13, 14],
       [16, 17]])

In [63]:
# There are other advanced methods of indexing which are shown below.
# integer indexing
e[[2, 0, 3, 1],[2, 1, 0, 2]] # first embedded list represent list trace row 2 from 0 to column 2 from 0

array([18, 11, 19, 15])

In [64]:
# boolean indexing meeting a specified condition
e[e>15]

array([16, 17, 18, 19, 20, 21])

In [71]:
# Intra-operability of arrays and scalars
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]], int)
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]], int)

In [72]:
c + d

array([[13, 13, 13],
       [10, 10, 10]])

In [73]:
c * d 

array([[36, 40, 42],
       [ 9, 16, 21]])

In [74]:
5 / d 

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [75]:
c ** 2

array([[81, 64, 49],
       [ 1,  4,  9]])