<a href="https://colab.research.google.com/github/ola-sumbo/Hamoye-and-ML-with-Ude/blob/master/Inbuilt_function_that_can_be_utilized_from_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse

from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()

import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

E: Package 'python-software-properties' has no installation candidate
Selecting previously unselected package google-drive-ocamlfuse.
(Reading database ... 144379 files and directories currently installed.)
Preparing to unpack .../google-drive-ocamlfuse_0.7.22-0ubuntu3~ubuntu18.04.1_amd64.deb ...
Unpacking google-drive-ocamlfuse (0.7.22-0ubuntu3~ubuntu18.04.1) ...
Setting up google-drive-ocamlfuse (0.7.22-0ubuntu3~ubuntu18.04.1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...


In [ ]:
!ls -ltr
!mkdir -p drive
!google-drive-ocamlfuse drive
%cd drive

In [1]:
# conversion for importing numpy 
import numpy as np

In [4]:
arr = [6, 7, 8, 9]
type(arr)


list

In [8]:
a = np.array(arr)
type(a)
a.shape
a.dtype

dtype('int64')

In [9]:
# Get dimension with ndim width
print(a.ndim)    #print 1

1


In [12]:
b = np.array([[1,2,3],[4,5,6]])
print(b) 
print(b.ndim)
print(b.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [ ]:
# Inbuilt function used to initialise numpy.py
# a 2 * 3 array generated with random variables
np.random.random

array([[0.44777134, 0.94154716, 0.18433596],
       [0.26216404, 0.36045223, 0.98642724]])

In [25]:
# a 2x3 array of zeros
np.zeros((2, 3))

np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
# a 3x3 identity matrix
s = np.zeros((3,3), int)
np.fill_diagonal(s,3) 
print(s)


[[3 0 0]
 [0 3 0]
 [0 0 3]]


In [36]:
# Indexing with arrays and using arrays for data processing 


array([0., 0., 0.])