<a href="https://colab.research.google.com/github/ola-sumbo/Hamoye-and-ML-with-Ude/blob/master/Inbuilt_function_that_can_be_utilized_from_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# conversion for importing numpy 
import numpy as np

In [4]:
arr = [6, 7, 8, 9]
type(arr)


list

In [8]:
a = np.array(arr)
type(a)
a.shape
a.dtype

dtype('int64')

In [9]:
# Get dimension with ndim width
print(a.ndim)    #print 1

1


In [12]:
b = np.array([[1,2,3],[4,5,6]])
print(b) 
print(b.ndim)
print(b.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [ ]:
# Inbuilt function used to initialise numpy.py
# a 2 * 3 array generated with random variables
np.random.random

array([[0.44777134, 0.94154716, 0.18433596],
       [0.26216404, 0.36045223, 0.98642724]])

In [25]:
# a 2x3 array of zeros
np.zeros((2, 3))

np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
# a 3x3 identity matrix
s = np.zeros((3,3), int)
np.fill_diagonal(s,3) 
print(s)


[[3 0 0]
 [0 3 0]
 [0 0 3]]


In [51]:
# Indexing with arrays and using arrays for data processing 
# The elements in the example arrays above can be accessed by indexing like lists in Python such that:
a[3] = 9
b[0, 0] # what is in the matrix of b at position 0 and o by index
b[1, 2] # look for index column 2 from 0 then at position of row 1 from 0



array([[1, 2, 3],
       [4, 5, 6]])